-- CreateEnum
CREATE TYPE "CaseType" AS ENUM ('TARIFF_UPDATE', 'PROVIDER_MANAGEMENT');

-- CreateEnum
CREATE TYPE "ProviderManagementCategory" AS ENUM ('PORTAL_LOGIN_ISSUE', 'PROVIDER_SIGN_UP_REQUEST', 'NEW_FACILITY_SIGN_ON', 'CONTACT_INFO_UPDATE', 'BANK_INFO_UPDATE', 'FACILITY_TIER_CHANGE', 'FULL_TARIFF_REVIEW_REQUEST', 'PROVIDER_SUSPENDED_US', 'PROVIDER_DEACTIVATION_REQUEST', 'COMPLIANCE_DOCUMENT_UPDATE', 'REPORT_ABUSE_FRAUD', 'REPORT_POOR_ENROLLEE_EXPERIENCE', 'OTHER');

-- AlterTable
ALTER TABLE "NegotiationCase"
  ADD COLUMN "caseType" "CaseType" NOT NULL DEFAULT 'TARIFF_UPDATE',
  ADD COLUMN "pmCategories" "ProviderManagementCategory"[] NOT NULL DEFAULT ARRAY[]::"ProviderManagementCategory"[],
  ADD COLUMN "pmAttachmentName" TEXT,
  ADD COLUMN "pmAttachmentMimeType" TEXT,
  ADD COLUMN "pmAttachmentData" BYTEA,
  ALTER COLUMN "serviceType" DROP NOT NULL,
  ALTER COLUMN "currentTariff" SET DEFAULT 0,
  ALTER COLUMN "providerRequestedAmount" SET DEFAULT 0;
