-- Replace ServiceType enum values with the new category list, remapping
-- any existing rows rather than dropping their data.
--   MEDICATION -> MEDICATIONS
--   DELIVERY   -> ADMISSION_RELATED_SERVICES
--   SURGERY    -> SURGERIES
--   LAB        -> INVESTIGATIONS
--   SCAN       -> INVESTIGATIONS
--   ADMISSION  -> ADMISSION_RELATED_SERVICES
--   PROCEDURE  -> PROCEDURES_AND_SERVICES
--   OTHERS     -> PROCEDURES_AND_SERVICES

CREATE TYPE "ServiceType_new" AS ENUM (
  'CONSULTATION',
  'MEDICATIONS',
  'INVESTIGATIONS',
  'ADMISSION_RELATED_SERVICES',
  'PROCEDURES_AND_SERVICES',
  'SURGERIES'
);

ALTER TABLE "NegotiationCase"
  ALTER COLUMN "serviceType" TYPE "ServiceType_new"
  USING (
    CASE "serviceType"::text
      WHEN 'MEDICATION' THEN 'MEDICATIONS'
      WHEN 'DELIVERY' THEN 'ADMISSION_RELATED_SERVICES'
      WHEN 'SURGERY' THEN 'SURGERIES'
      WHEN 'LAB' THEN 'INVESTIGATIONS'
      WHEN 'SCAN' THEN 'INVESTIGATIONS'
      WHEN 'ADMISSION' THEN 'ADMISSION_RELATED_SERVICES'
      WHEN 'PROCEDURE' THEN 'PROCEDURES_AND_SERVICES'
      WHEN 'OTHERS' THEN 'PROCEDURES_AND_SERVICES'
    END
  )::"ServiceType_new";

DROP TYPE "ServiceType";
ALTER TYPE "ServiceType_new" RENAME TO "ServiceType";
